### ISSUE TITLE
Undocumented dependencies

### ISSUE THREAD

**Issue by ryanberry** [sevenwestmedia/project-watchtower#17]
The following were needed as dependencies, couldn't spot any documentation about it: 
`cheerio`
`react-router`
`react-router-dom`
`cache-loader`
`thread-loader`

**Comment by intelseb** [comment]
Node will notify you of any peer dependencies

**Comment by JakeGinnivan** [comment]
Dependencies have been cleaned up now and should warn if not installed. Main issue was cheerio which is gone now that stats has gone
